CREATE TYPE "OpportunityDeliveryStatus" AS ENUM ('NOT_STARTED', 'KICKOFF_SCHEDULED', 'PAPERWORK_COMPLETE', 'IMPLEMENTATION_IN_PROGRESS', 'INSTALL_SCHEDULED', 'LIVE', 'FOLLOW_UP_COMPLETE');

ALTER TABLE "Opportunity"
ADD COLUMN "deliveryStatus" "OpportunityDeliveryStatus";
